"""
Base django settings for finli project

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from typing import List, Dict, Any
from pathlib import Path

# Показывает константу среды запуска для отладки работы окружения
FINLI_ENV: str = 'ENV_BASE'

# Build paths inside the project like this: BASE_DIR / 'subdir'
BASE_DIR: Path = Path(__file__).resolve().parent.parent.parent
FINLI_DIR: Path = BASE_DIR / 'finli'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY: str = 'django-insecure-fe#jrwm)sqo3%h!#gr##lg$b1vz!t27&st#537z8^82*kchsk%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG: bool = False

ALLOWED_HOSTS: List[str] = ['fin-li.ru']


# Application definition

INSTALLED_APPS: List[str] = [
    'main_app',
    'debug_app',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE: List[str] = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF: str = 'finli.urls'
TEMPLATE_DIR: str = os.path.join(BASE_DIR, 'templates')

TEMPLATES: List[Any] = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION: str = 'finli.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES: Dict[str, Any]

FINLI_DB_TYPE_VALUES: List[str] = ['mysql', 'sqlite']
FINLI_DB_TYPE_DEFAULT: str = 'sqlite'
FINLI_DB_TYPE: str = str(os.environ.get('FINLI_DB_TYPE', FINLI_DB_TYPE_DEFAULT)).upper()
finli_db_type_value: str = str(FINLI_DB_TYPE).lower()

if finli_db_type_value not in FINLI_DB_TYPE_VALUES:
    raise ValueError('Нат такой конфигурации базы данных: ' + finli_db_type_value)
else:
    # Настройка для sqlite3
    if finli_db_type_value == 'sqlite':
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

    # Настройка для MySQL/MariaDB
    elif finli_db_type_value == 'mysql':

        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': 'finli_prod',
                'USER': 'finli_prod',
                'PASSWORD': '02Mt13kX2CAgsVCV',
                'HOST': 'localhost',  # localhost - for unix-socket, 127.0.0.1 - for tcp/ip
                'PORT': '3306',
            }
        }
    else:
        raise ValueError('Возможно забыли добавить конфигурацию??')


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS: List[Dict[str, str]] = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE: str = 'en-us'

TIME_ZONE: str = 'UTC'

USE_I18N: bool = True

USE_TZ: bool = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL: str = '/static/'
STATIC_ROOT: str = 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD: str = 'django.db.models.BigAutoField'
