# Generated by Django 5.1.1 on 2024-11-28 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productinstance')),
                ('property_instances', models.ManyToManyField(blank=True, to='main.propertyinstance')),
            ],
        ),
    ]
