# Generated by Django 5.0.7 on 2024-09-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_imagesinstance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagesinstance",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
