# Generated by Django 5.1.1 on 2024-11-28 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='property_instances',
        ),
        migrations.AddField(
            model_name='stock',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='stock_configs', to='main.propertyinstance'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='main.productinstance'),
        ),
    ]
