# Generated by Django 5.1.1 on 2024-11-28 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_stock_property_instances_stock_properties_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='properties',
        ),
        migrations.AddField(
            model_name='stock',
            name='property_instances',
            field=models.ManyToManyField(blank=True, to='main.propertyinstance'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productinstance'),
        ),
    ]
