# Generated by Django 5.0.7 on 2024-09-11 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_imagesinstance_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyinstance",
            name="image_instance_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.imagesinstance",
            ),
        ),
        migrations.AlterField(
            model_name="imagesinstance",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
