# Generated by Django 5.0.7 on 2024-09-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_propertyinstance_image_instance_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinstance",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
