# Generated by Django 5.1 on 2024-09-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productinstance_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyinstance',
            name='image_instance_id',
        ),
    ]
