# Generated by Django 5.0.7 on 2024-09-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_productinstance_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyinstance",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
