# Generated by Django 5.0.7 on 2024-09-21 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_propertyinstance_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyinstance",
            name="slug",
        ),
    ]
