# Generated by Django 5.1.1 on 2024-09-27 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_remove_propertyinstance_image_instance_id"),
        ("main", "0007_remove_propertyinstance_slug"),
    ]

    operations = []
